// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inmpevwtfzhgynkermim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubXBldnd0ZnpoZ3lua2VybWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMjM0NDQsImV4cCI6MjA2OTU5OTQ0NH0.ulWwCjwl-fWrs7gRqXV-37DfWVx15azkhUmSoWoQk7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});